### PR TITLE
99-empty-screen-for-demo-section

### PR DESCRIPTION
**Pull request by Adhithyarajan**
created two empty screens for demo section.

### CODE REVIEW

**Comment by ajayesivan** [comment]
@Adhithyarajan Could you please fix conflicts and update the PR

**Comment by ajayesivan** [comment]
Also please link the related issue.

**Comment by ajayesivan** [comment]
@Adhithyarajan The conflicts haven't been resolved. You can status of the PR at the bottom of the PR conversations page in GitHub. Check the below image.

Screenshot 2023-07-01 at 16 37 15


Let me know if you need assistance in resolving conflicts.

**Comment by Adhithyarajan** [comment]
When I resolved conflict and commit. It shows the page is out of date,Start over. When i click startover and done the same, it still shows same error message.

**Comment by ajayesivan** [comment]
@Adhithyarajan It appears to be an issue on GitHub's side. Your branch has two commits, including the merge commit, but in your PR, it only shows 1 commit. I'm not certain why this occurred. Please take a look at [this video](https://www.loom.com/share/b2985c8e73bb4a54abfe52d967eeb9b0?sid=e570a3ff-b803-4828-a1ba-b7c0e494b266) for more information and try the suggested solution.

**Pull request closed without merging**
